# Generated by Django 3.2.9 on 2021-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="user_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
